# This file was generated by GoReleaser. DO NOT EDIT.
cask "claudeline" do
  version "1.1.1"

  on_macos do
    on_intel do
      url "https://github.com/lexfrei/claudeline/releases/download/v#{version}/claudeline_darwin_amd64.tar.gz"
      sha256 "13b2a0d254e64445886f964d0c3b339703ff21e81c679d9604c3890d06189941"
    end
    on_arm do
      url "https://github.com/lexfrei/claudeline/releases/download/v#{version}/claudeline_darwin_arm64.tar.gz"
      sha256 "9c02298ff45099cd7bc7bc512bd1c0fcad5bc3f54b377e8612c68904ea58f28b"
    end
  end

  name "claudeline"
  desc "Real-time statusline for Claude Code"
  homepage "https://github.com/lexfrei/claudeline"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "claudeline"

  # No zap stanza required

end
