# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ailine < Formula
  desc "Real-time statusline for Claude Code"
  homepage "https://github.com/lexfrei/ailine"
  version "1.11.1"
  license "BSD-3-Clause"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lexfrei/ailine/releases/download/v1.11.1/ailine_darwin_amd64.tar.gz"
      sha256 "d69cbf6ef6f66ce03cfc3ecdaa7e5db135f460b8c555443072423b42632f26f3"

      define_method(:install) do
        bin.install "ailine"
        bin.install_symlink "ailine" => "claudeline"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lexfrei/ailine/releases/download/v1.11.1/ailine_darwin_arm64.tar.gz"
      sha256 "019b0ae2f20c305e3ab3ee70b3918df691eb0f5cbb86f08fa0dca67bfc2b657e"

      define_method(:install) do
        bin.install "ailine"
        bin.install_symlink "ailine" => "claudeline"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lexfrei/ailine/releases/download/v1.11.1/ailine_linux_amd64.tar.gz"
      sha256 "8d1d5ddfde9b3a7c4bdd9f84d011bb5abbd51b11177dac7ab5086ce1bc9988c3"
      define_method(:install) do
        bin.install "ailine"
        bin.install_symlink "ailine" => "claudeline"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lexfrei/ailine/releases/download/v1.11.1/ailine_linux_arm64.tar.gz"
      sha256 "8a51fb9c768ac574da3d1f79e349a55d37c772e2805d705fedadebbd7c00e503"
      define_method(:install) do
        bin.install "ailine"
        bin.install_symlink "ailine" => "claudeline"
      end
    end
  end
end
