# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ailine < Formula
  desc "Real-time statusline for Claude Code"
  homepage "https://github.com/lexfrei/ailine"
  version "1.10.2"
  license "BSD-3-Clause"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lexfrei/ailine/releases/download/v1.10.2/ailine_darwin_amd64.tar.gz"
      sha256 "31ff01c7b5746c3dda67405e14a2ac39bde957d330ec33ab09e04dee45cbf8cd"

      define_method(:install) do
        bin.install "ailine"
        bin.install_symlink "ailine" => "claudeline"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lexfrei/ailine/releases/download/v1.10.2/ailine_darwin_arm64.tar.gz"
      sha256 "83f0ff1ca194b1b803d8793207a6cd336ec4ba7d099b0875379e5e0ba26b292f"

      define_method(:install) do
        bin.install "ailine"
        bin.install_symlink "ailine" => "claudeline"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lexfrei/ailine/releases/download/v1.10.2/ailine_linux_amd64.tar.gz"
      sha256 "2830c1394b56af56f0cb39153e8337734df088d5e0daf9a9388c7092e527c6f2"
      define_method(:install) do
        bin.install "ailine"
        bin.install_symlink "ailine" => "claudeline"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lexfrei/ailine/releases/download/v1.10.2/ailine_linux_arm64.tar.gz"
      sha256 "02830e83fec6c07d72e0f81d348a9f50462ff2c7ed0a696acacd88d5b8d046b2"
      define_method(:install) do
        bin.install "ailine"
        bin.install_symlink "ailine" => "claudeline"
      end
    end
  end
end
