# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ailine < Formula
  desc "Real-time statusline for Claude Code"
  homepage "https://github.com/lexfrei/ailine"
  version "1.11.0"
  license "BSD-3-Clause"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lexfrei/ailine/releases/download/v1.11.0/ailine_darwin_amd64.tar.gz"
      sha256 "c23ca2ae987098ce93e0eec29472d035ad0813d62ea135e6f072a10c0e023db7"

      define_method(:install) do
        bin.install "ailine"
        bin.install_symlink "ailine" => "claudeline"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lexfrei/ailine/releases/download/v1.11.0/ailine_darwin_arm64.tar.gz"
      sha256 "50b5872c08b7b0603ea0049731822ee4346c669d8cc6ed24638c73c3a3c01749"

      define_method(:install) do
        bin.install "ailine"
        bin.install_symlink "ailine" => "claudeline"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lexfrei/ailine/releases/download/v1.11.0/ailine_linux_amd64.tar.gz"
      sha256 "a33dab1cd75ba967e4d36f475339010bcb426b1e50b5f05c0dd8c324c1544ef3"
      define_method(:install) do
        bin.install "ailine"
        bin.install_symlink "ailine" => "claudeline"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lexfrei/ailine/releases/download/v1.11.0/ailine_linux_arm64.tar.gz"
      sha256 "d8014187a2869ca0b5bdefb4254662f5962fbc4e065e008037443845bc9ba731"
      define_method(:install) do
        bin.install "ailine"
        bin.install_symlink "ailine" => "claudeline"
      end
    end
  end
end
