# typed: false
# frozen_string_literal: true

# This file is generated by scripts/brew-bump.sh in lexfrei/macro-claude.
# Do not edit by hand — run 'make brew-bump TAG=vX.Y.Z' instead.
class MacroClaude < Formula
  desc "Logi MX Creative Console plugin showing Claude Code session statuses"
  homepage "https://github.com/lexfrei/macro-claude"
  version "0.2.2"
  url "https://github.com/lexfrei/macro-claude/releases/download/v0.2.2/MacroClaudePlugin.lplug4"
  sha256 "dd833e48fe446a61b4c85a6a2abfe6cc4a37036a794bfe5cf067f73790ee700c"
  license "MIT"
  depends_on :macos

  def install
    # .lplug4 is a zip archive of the LPS plugin package (bin/ + metadata/).
    system "unzip", "-q", cached_download, "-d", libexec
  end

  def caveats
    plugins_dir = "$HOME/Library/Application Support/Logi/LogiPluginService/Plugins"
    <<~EOS
      Point Logi Plugin Service at the brew-managed copy by writing a
      .link file with the install prefix:

        printf '%s' '#{libexec}' > \\
          "#{plugins_dir}/MacroClaudePlugin.link"

      Touch the same file to force LPS to reload it. Before
      'brew uninstall macro-claude', remove the .link file:

        rm -f "#{plugins_dir}/MacroClaudePlugin.link"
    EOS
  end

  test do
    assert_predicate libexec/"bin/MacroClaudePlugin.dll", :exist?
    assert_predicate libexec/"metadata/LoupedeckPackage.yaml", :exist?
  end
end
