# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class McpTg < Formula
  desc "MCP server for the Telegram Client API (MTProto, user account)"
  homepage "https://github.com/lexfrei/mcp-tg"
  version "1.2.1"
  license "BSD-3-Clause"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lexfrei/mcp-tg/releases/download/v1.2.1/mcp-tg_1.2.1_darwin_amd64.tar.gz"
      sha256 "73993c1465b8aeb5bc60f780f3bd7ddb0186744da9e2a7f959897756d092af26"

      define_method(:install) do
        bin.install "mcp-tg"

        # brew services only passes the variables declared in `service` below,
        # and the credentials cannot be baked into a public formula. Ship a
        # config file under etc (Homebrew preserves it across upgrades) and a
        # wrapper that sources it, so the daemon starts configured.
        (etc/"mcp-tg").mkpath
        env_file = etc/"mcp-tg/mcp-tg.env"
        unless env_file.exist?
          # Credentials, and the only file the docs tell people to edit. The
          # session file is 0600 and the default backend is the OS keychain;
          # this must not be the world-readable exception.
          env_file.write <<~CONF
            # Credentials from https://my.telegram.org/apps — required.
            TELEGRAM_APP_ID=
            TELEGRAM_APP_HASH=
            # Uncomment ONLY if you logged in with --insecure-storage; the
            # session backend must match on both sides.
            # TELEGRAM_SESSION_INSECURE=true
          CONF
          chmod 0600, env_file
        end

        (libexec/"mcp-tg-daemon").write <<~SH
          #!/bin/sh
          set -a
          [ -f "#{etc}/mcp-tg/mcp-tg.env" ] && . "#{etc}/mcp-tg/mcp-tg.env"
          set +a
          exec "#{opt_bin}/mcp-tg" "$@"
        SH
        chmod 0755, libexec/"mcp-tg-daemon"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lexfrei/mcp-tg/releases/download/v1.2.1/mcp-tg_1.2.1_darwin_arm64.tar.gz"
      sha256 "fa6ff5a8e76c3bb63223963f34832836bb5581433c3a9433629d83f87152284a"

      define_method(:install) do
        bin.install "mcp-tg"

        # brew services only passes the variables declared in `service` below,
        # and the credentials cannot be baked into a public formula. Ship a
        # config file under etc (Homebrew preserves it across upgrades) and a
        # wrapper that sources it, so the daemon starts configured.
        (etc/"mcp-tg").mkpath
        env_file = etc/"mcp-tg/mcp-tg.env"
        unless env_file.exist?
          # Credentials, and the only file the docs tell people to edit. The
          # session file is 0600 and the default backend is the OS keychain;
          # this must not be the world-readable exception.
          env_file.write <<~CONF
            # Credentials from https://my.telegram.org/apps — required.
            TELEGRAM_APP_ID=
            TELEGRAM_APP_HASH=
            # Uncomment ONLY if you logged in with --insecure-storage; the
            # session backend must match on both sides.
            # TELEGRAM_SESSION_INSECURE=true
          CONF
          chmod 0600, env_file
        end

        (libexec/"mcp-tg-daemon").write <<~SH
          #!/bin/sh
          set -a
          [ -f "#{etc}/mcp-tg/mcp-tg.env" ] && . "#{etc}/mcp-tg/mcp-tg.env"
          set +a
          exec "#{opt_bin}/mcp-tg" "$@"
        SH
        chmod 0755, libexec/"mcp-tg-daemon"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lexfrei/mcp-tg/releases/download/v1.2.1/mcp-tg_1.2.1_linux_amd64.tar.gz"
      sha256 "a72f6c3b7c89e909d51054e83fb73ebbfc35e38ebfb8dd5d738afffea3a0cbe3"
      define_method(:install) do
        bin.install "mcp-tg"

        # brew services only passes the variables declared in `service` below,
        # and the credentials cannot be baked into a public formula. Ship a
        # config file under etc (Homebrew preserves it across upgrades) and a
        # wrapper that sources it, so the daemon starts configured.
        (etc/"mcp-tg").mkpath
        env_file = etc/"mcp-tg/mcp-tg.env"
        unless env_file.exist?
          # Credentials, and the only file the docs tell people to edit. The
          # session file is 0600 and the default backend is the OS keychain;
          # this must not be the world-readable exception.
          env_file.write <<~CONF
            # Credentials from https://my.telegram.org/apps — required.
            TELEGRAM_APP_ID=
            TELEGRAM_APP_HASH=
            # Uncomment ONLY if you logged in with --insecure-storage; the
            # session backend must match on both sides.
            # TELEGRAM_SESSION_INSECURE=true
          CONF
          chmod 0600, env_file
        end

        (libexec/"mcp-tg-daemon").write <<~SH
          #!/bin/sh
          set -a
          [ -f "#{etc}/mcp-tg/mcp-tg.env" ] && . "#{etc}/mcp-tg/mcp-tg.env"
          set +a
          exec "#{opt_bin}/mcp-tg" "$@"
        SH
        chmod 0755, libexec/"mcp-tg-daemon"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lexfrei/mcp-tg/releases/download/v1.2.1/mcp-tg_1.2.1_linux_arm64.tar.gz"
      sha256 "364cc7955791cd64c43f6471363a221d43d5365a7621cd189f1115ca64406b9a"
      define_method(:install) do
        bin.install "mcp-tg"

        # brew services only passes the variables declared in `service` below,
        # and the credentials cannot be baked into a public formula. Ship a
        # config file under etc (Homebrew preserves it across upgrades) and a
        # wrapper that sources it, so the daemon starts configured.
        (etc/"mcp-tg").mkpath
        env_file = etc/"mcp-tg/mcp-tg.env"
        unless env_file.exist?
          # Credentials, and the only file the docs tell people to edit. The
          # session file is 0600 and the default backend is the OS keychain;
          # this must not be the world-readable exception.
          env_file.write <<~CONF
            # Credentials from https://my.telegram.org/apps — required.
            TELEGRAM_APP_ID=
            TELEGRAM_APP_HASH=
            # Uncomment ONLY if you logged in with --insecure-storage; the
            # session backend must match on both sides.
            # TELEGRAM_SESSION_INSECURE=true
          CONF
          chmod 0600, env_file
        end

        (libexec/"mcp-tg-daemon").write <<~SH
          #!/bin/sh
          set -a
          [ -f "#{etc}/mcp-tg/mcp-tg.env" ] && . "#{etc}/mcp-tg/mcp-tg.env"
          set +a
          exec "#{opt_bin}/mcp-tg" "$@"
        SH
        chmod 0755, libexec/"mcp-tg-daemon"
      end
    end
  end

  def caveats
    <<~EOS
      The public build ships no Telegram credentials, and the daemon cannot log
      in by itself. Three steps, then it survives reboots on its own:

        1. Put an app id and hash from https://my.telegram.org/apps into

             #{etc}/mcp-tg/mcp-tg.env

        2. Log in interactively (the same file feeds this shell):

             set -a; . #{etc}/mcp-tg/mcp-tg.env; set +a
             mcp-tg login

           The session goes to the OS keychain. Use --insecure-storage only if
           the machine has no keychain (a container, or headless Linux without a
           Secret Service) — and then uncomment TELEGRAM_SESSION_INSECURE in the
           same file, because the backend must match on both sides.

        3. Start the shared daemon on 127.0.0.1:8787:

             brew services start mcp-tg

           Do this AFTER step 1 — started with the file still empty, the daemon
           exits on every launch and the service manager keeps restarting it.

           Do NOT use `sudo brew services start`: that installs a LaunchDaemon,
           which runs as root and reads the SYSTEM keychain, while `mcp-tg
           login` wrote the session to YOUR login keychain (and root's HOME is
           different too). The daemon would report a missing session and tell
           you to log in, which you already did.

      The service sources that file on every start, so nothing depends on your
      login shell. If it crash-loops, the config is the first suspect: check
      `brew services list` and $(brew --prefix)/var/log/mcp-tg.log.

      Homebrew keeps files under etc across upgrades AND uninstalls, so the
      credentials outlive `brew uninstall mcp-tg` — delete the file yourself if
      you mean to remove them.
    EOS
  end

  service do
    run [opt_libexec/"mcp-tg-daemon"]
    keep_alive true
    log_path var/"log/mcp-tg.log"
    error_log_path var/"log/mcp-tg.log"
    environment_variables MCP_HTTP_ONLY: "true", MCP_HTTP_HOST: "127.0.0.1", MCP_HTTP_PORT: "8787"
  end

  test do
    # The binary has no --version flag and every real command talks to
    # Telegram, so missing credentials is the only offline path. The vars
    # must be cleared explicitly: the caveats tell users to export them, and
    # with them set the process opens a live MTProto connection and never
    # returns — brew test would hang.
    assert_match "TELEGRAM_APP_ID is required",
      shell_output("TELEGRAM_APP_ID= TELEGRAM_APP_HASH= #{bin}/mcp-tg 2>&1", 1)
  end
end
