# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class McpTg < Formula
  desc "MCP server for the Telegram Client API (MTProto, user account)"
  homepage "https://github.com/lexfrei/mcp-tg"
  version "1.4.0"
  license "BSD-3-Clause"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lexfrei/mcp-tg/releases/download/v1.4.0/mcp-tg_1.4.0_darwin_amd64.tar.gz"
      sha256 "4b253ea304d29c39ddbfe32dc9261a449f4b33449532f4a703aa7b88938ddb53"

      define_method(:install) do
        bin.install "mcp-tg"

        # brew services only passes the variables declared in `service` below,
        # and the credentials cannot be baked into a public formula. Ship a
        # config file under etc (Homebrew preserves it across upgrades) and a
        # wrapper that sources it, so the daemon starts configured.
        (etc/"mcp-tg").mkpath
        env_file = etc/"mcp-tg/mcp-tg.env"
        unless env_file.exist?
          # Credentials, and the only file the docs tell people to edit. The
          # session file is 0600 and the default backend is the OS keychain;
          # this must not be the world-readable exception.
          env_file.write <<~CONF
            # Credentials from https://my.telegram.org/apps — required.
            TELEGRAM_APP_ID=
            TELEGRAM_APP_HASH=
            # Uncomment ONLY if you logged in with --insecure-storage; the
            # session backend must match on both sides.
            # TELEGRAM_SESSION_INSECURE=true
          CONF
          chmod 0600, env_file
        end

        (libexec/"mcp-tg-daemon").write <<~SH
          #!/bin/sh
          set -a
          [ -f "#{etc}/mcp-tg/mcp-tg.env" ] && . "#{etc}/mcp-tg/mcp-tg.env"
          set +a
          exec "#{opt_bin}/mcp-tg" "$@"
        SH
        chmod 0755, libexec/"mcp-tg-daemon"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lexfrei/mcp-tg/releases/download/v1.4.0/mcp-tg_1.4.0_darwin_arm64.tar.gz"
      sha256 "abe3c163ffb56e3c6752bb9c4a58d6f86fb3c17cc0d332b7c93e1371ee3c0f9c"

      define_method(:install) do
        bin.install "mcp-tg"

        # brew services only passes the variables declared in `service` below,
        # and the credentials cannot be baked into a public formula. Ship a
        # config file under etc (Homebrew preserves it across upgrades) and a
        # wrapper that sources it, so the daemon starts configured.
        (etc/"mcp-tg").mkpath
        env_file = etc/"mcp-tg/mcp-tg.env"
        unless env_file.exist?
          # Credentials, and the only file the docs tell people to edit. The
          # session file is 0600 and the default backend is the OS keychain;
          # this must not be the world-readable exception.
          env_file.write <<~CONF
            # Credentials from https://my.telegram.org/apps — required.
            TELEGRAM_APP_ID=
            TELEGRAM_APP_HASH=
            # Uncomment ONLY if you logged in with --insecure-storage; the
            # session backend must match on both sides.
            # TELEGRAM_SESSION_INSECURE=true
          CONF
          chmod 0600, env_file
        end

        (libexec/"mcp-tg-daemon").write <<~SH
          #!/bin/sh
          set -a
          [ -f "#{etc}/mcp-tg/mcp-tg.env" ] && . "#{etc}/mcp-tg/mcp-tg.env"
          set +a
          exec "#{opt_bin}/mcp-tg" "$@"
        SH
        chmod 0755, libexec/"mcp-tg-daemon"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lexfrei/mcp-tg/releases/download/v1.4.0/mcp-tg_1.4.0_linux_amd64.tar.gz"
      sha256 "269c25cbd2f981468d400656213ad2357b8ce9c0ccd3b6bdb90d5d85957428f5"
      define_method(:install) do
        bin.install "mcp-tg"

        # brew services only passes the variables declared in `service` below,
        # and the credentials cannot be baked into a public formula. Ship a
        # config file under etc (Homebrew preserves it across upgrades) and a
        # wrapper that sources it, so the daemon starts configured.
        (etc/"mcp-tg").mkpath
        env_file = etc/"mcp-tg/mcp-tg.env"
        unless env_file.exist?
          # Credentials, and the only file the docs tell people to edit. The
          # session file is 0600 and the default backend is the OS keychain;
          # this must not be the world-readable exception.
          env_file.write <<~CONF
            # Credentials from https://my.telegram.org/apps — required.
            TELEGRAM_APP_ID=
            TELEGRAM_APP_HASH=
            # Uncomment ONLY if you logged in with --insecure-storage; the
            # session backend must match on both sides.
            # TELEGRAM_SESSION_INSECURE=true
          CONF
          chmod 0600, env_file
        end

        (libexec/"mcp-tg-daemon").write <<~SH
          #!/bin/sh
          set -a
          [ -f "#{etc}/mcp-tg/mcp-tg.env" ] && . "#{etc}/mcp-tg/mcp-tg.env"
          set +a
          exec "#{opt_bin}/mcp-tg" "$@"
        SH
        chmod 0755, libexec/"mcp-tg-daemon"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lexfrei/mcp-tg/releases/download/v1.4.0/mcp-tg_1.4.0_linux_arm64.tar.gz"
      sha256 "f76edb19605f3fd4161b724bba0bd90f21d38e125717da811f53a18628377604"
      define_method(:install) do
        bin.install "mcp-tg"

        # brew services only passes the variables declared in `service` below,
        # and the credentials cannot be baked into a public formula. Ship a
        # config file under etc (Homebrew preserves it across upgrades) and a
        # wrapper that sources it, so the daemon starts configured.
        (etc/"mcp-tg").mkpath
        env_file = etc/"mcp-tg/mcp-tg.env"
        unless env_file.exist?
          # Credentials, and the only file the docs tell people to edit. The
          # session file is 0600 and the default backend is the OS keychain;
          # this must not be the world-readable exception.
          env_file.write <<~CONF
            # Credentials from https://my.telegram.org/apps — required.
            TELEGRAM_APP_ID=
            TELEGRAM_APP_HASH=
            # Uncomment ONLY if you logged in with --insecure-storage; the
            # session backend must match on both sides.
            # TELEGRAM_SESSION_INSECURE=true
          CONF
          chmod 0600, env_file
        end

        (libexec/"mcp-tg-daemon").write <<~SH
          #!/bin/sh
          set -a
          [ -f "#{etc}/mcp-tg/mcp-tg.env" ] && . "#{etc}/mcp-tg/mcp-tg.env"
          set +a
          exec "#{opt_bin}/mcp-tg" "$@"
        SH
        chmod 0755, libexec/"mcp-tg-daemon"
      end
    end
  end

  def caveats
    <<~EOS
      The public build ships no Telegram credentials, and the daemon cannot log
      in by itself. Three steps, then it survives reboots on its own:

        1. Put an app id and hash from https://my.telegram.org/apps into

             #{etc}/mcp-tg/mcp-tg.env

        2. Log in interactively (the same file feeds this shell):

             set -a; . #{etc}/mcp-tg/mcp-tg.env; set +a
             mcp-tg login

           The session goes to the OS keychain. Use --insecure-storage only if
           the machine has no keychain (a container, or headless Linux without a
           Secret Service) — and then uncomment TELEGRAM_SESSION_INSECURE in the
           same file, because the backend must match on both sides.

        3. Start the shared daemon on 127.0.0.1:8787:

             brew services start mcp-tg

           Do this AFTER step 1 — started with the file still empty, the daemon
           exits on every launch and the service manager keeps restarting it.

           Do NOT use `sudo brew services start`: that installs a LaunchDaemon,
           which runs as root and reads the SYSTEM keychain, while `mcp-tg
           login` wrote the session to YOUR login keychain (and root's HOME is
           different too). The daemon would report a missing session and tell
           you to log in, which you already did.

      The service sources that file on every start, so nothing depends on your
      login shell. If it crash-loops, the config is the first suspect: check
      `brew services list` and $(brew --prefix)/var/log/mcp-tg.log.

      Homebrew keeps files under etc across upgrades AND uninstalls, so the
      credentials outlive `brew uninstall mcp-tg` — delete the file yourself if
      you mean to remove them.
    EOS
  end

  service do
    run [opt_libexec/"mcp-tg-daemon"]
    keep_alive true
    log_path var/"log/mcp-tg.log"
    error_log_path var/"log/mcp-tg.log"
    environment_variables MCP_HTTP_ONLY: "true", MCP_HTTP_HOST: "127.0.0.1", MCP_HTTP_PORT: "8787"
  end

  test do
    # Every real command talks to Telegram, so both checks here are the ones
    # that stay offline. The credentials must be cleared explicitly: the
    # caveats tell users to export them, and with them set the process opens
    # a live MTProto connection and never returns — brew test would hang.
    assert_match "TELEGRAM_APP_ID is required",
      shell_output("TELEGRAM_APP_ID= TELEGRAM_APP_HASH= #{bin}/mcp-tg 2>&1", 1)
    # --version exits before any Telegram work, and it is the only thing that
    # checks the ldflags above reached this build: the linker ignores -X for a
    # symbol that does not exist without a word, so a rename would ship a
    # formula whose every release introduces itself as "dev". Homebrew's
    # `version` has no leading v, and the build line carries it as a substring.
    assert_match version.to_s, shell_output("#{bin}/mcp-tg --version")
  end
end
